
import type { Show, Club, ShowStatus } from "@/types";

export const mockShows: Show[] = [
  {
    id: "1",
    title: "Cosmic Wonders",
    description: "An epic journey through space and time, exploring the universe's greatest mysteries. Contains plot twists in season 2.",
    coverImageUrl: "https://picsum.photos/seed/cosmic/300/450",
    totalEpisodes: 20,
    watchedEpisodes: 10,
    status: "Watching",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    rating: 9.2,
    spoilersVisible: false,
    userScore: 9,
    releaseYear: 2022,
  },
  {
    id: "2",
    title: "Cybernetic City",
    description: "In a futuristic metropolis, a detective uncovers a conspiracy that reaches the highest levels of power. The main character's fate is revealed in the finale.",
    coverImageUrl: "https://picsum.photos/seed/cyber/300/450",
    totalEpisodes: 12,
    watchedEpisodes: 12,
    status: "Completed",
    genres: ["Cyberpunk", "Thriller", "Mystery"],
    rating: 8.8,
    spoilersVisible: true,
    userScore: 8,
    releaseYear: 2021,
  },
  {
    id: "3",
    title: "The Last Kingdom",
    description: "A historical drama following the life of Uhtred of Bebbanburg during the Viking invasions of England. Major character deaths occur frequently.",
    coverImageUrl: "https://picsum.photos/seed/kingdom/300/450",
    totalEpisodes: 46,
    watchedEpisodes: 20,
    status: "On Hold",
    genres: ["Historical Fiction", "Action", "Drama"],
    rating: 8.5,
    spoilersVisible: false,
    userScore: 7,
    releaseYear: 2015,
  },
  {
    id: "4",
    title: "Mystic Peaks",
    description: "A small town is plagued by supernatural occurrences after a mysterious artifact is discovered. The source of the mystery is unveiled at the end of season 1.",
    coverImageUrl: "https://picsum.photos/seed/mystic/300/450",
    totalEpisodes: 8,
    watchedEpisodes: 3,
    status: "Dropped",
    genres: ["Supernatural", "Horror", "Mystery"],
    rating: 7.0,
    spoilersVisible: false,
    releaseYear: 2023,
  },
  {
    id: "5",
    title: "Galactic Guardians",
    description: "A team of unlikely heroes band together to protect the galaxy from an ancient evil. Features a surprise villain reveal.",
    coverImageUrl: "https://picsum.photos/seed/galactic/300/450",
    totalEpisodes: 24,
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Sci-Fi", "Action", "Comedy"],
    rating: 9.0,
    spoilersVisible: false,
    releaseYear: 2024,
  },
  {
    id: "6",
    title: "Chronicles of Eldoria",
    description: "A sprawling fantasy epic about a young sorceress destined to save her world from encroaching darkness. The prophecy is a key plot point.",
    coverImageUrl: "https://picsum.photos/seed/eldoria/300/450",
    totalEpisodes: 10,
    watchedEpisodes: 5,
    status: "Watching",
    genres: ["Fantasy", "Adventure"],
    rating: 8.9,
    spoilersVisible: false,
    userScore: 9,
    releaseYear: 2023,
  },
];

export const mockClubs: Club[] = [
  {
    id: "c1",
    name: "Sci-Fi Mavericks",
    description: "A club for lovers of all things science fiction, from classic novels to modern blockbusters.",
    memberCount: 125,
    coverImageUrl: "https://picsum.photos/seed/scificlub/400/200",
    tags: ["Sci-Fi", "Movies", "TV Shows", "Books"],
  },
  {
    id: "c2",
    name: "Fantasy Fanatics",
    description: "Discuss your favorite fantasy series, theories, and upcoming adaptations.",
    memberCount: 210,
    coverImageUrl: "https://picsum.photos/seed/fantasyclub/400/200",
    tags: ["Fantasy", "Epic Fantasy", "Urban Fantasy"],
  },
  {
    id: "c3",
    name: "Anime Watchers Unite",
    description: "From Shonen to Shojo, seasonal anime discussions and recommendations.",
    memberCount: 350,
    coverImageUrl: "https://picsum.photos/seed/animeclub/400/200",
    tags: ["Anime", "Manga", "Seasonal"],
  },
   {
    id: "c4",
    name: "Thriller Thursday",
    description: "Dedicated to suspenseful thrillers and mind-bending mysteries.",
    memberCount: 88,
    coverImageUrl: "https://picsum.photos/seed/thrillerclub/400/200",
    tags: ["Thriller", "Mystery", "Suspense", "Crime"],
  },
];
