
import type { Show, Club } from "@/types";

export const mockShows: Show[] = [
  {
    id: "1",
    title: "Cosmic Wonders",
    description: "An epic journey through space and time, exploring the universe's greatest mysteries. Contains plot twists in season 2.",
    coverImageUrl: "https://picsum.photos/seed/cosmic/300/450",
    totalEpisodes: 20,
    watchedEpisodes: 10,
    status: "Watching",
    genres: ["Sci-Fi", "Adventure", "Drama"],
    rating: 9.2,
    spoilersVisible: false,
    userScore: 9,
    releaseYear: 2022,
  },
  {
    id: "2",
    title: "Cybernetic City",
    description: "In a futuristic metropolis, a detective uncovers a conspiracy that reaches the highest levels of power. The main character's fate is revealed in the finale.",
    coverImageUrl: "https://picsum.photos/seed/cyber/300/450",
    totalEpisodes: 12,
    watchedEpisodes: 12,
    status: "Completed",
    genres: ["Cyberpunk", "Thriller", "Mystery"],
    rating: 8.8,
    spoilersVisible: true,
    userScore: 8,
    releaseYear: 2021,
  },
  {
    id: "3",
    title: "The Last Kingdom",
    description: "A historical drama following the life of Uhtred of Bebbanburg during the Viking invasions of England. Major character deaths occur frequently.",
    coverImageUrl: "https://picsum.photos/seed/kingdom/300/450",
    totalEpisodes: 46,
    watchedEpisodes: 20,
    status: "On Hold",
    genres: ["Historical Fiction", "Action", "Drama"],
    rating: 8.5,
    spoilersVisible: false,
    userScore: 7,
    releaseYear: 2015,
  },
  {
    id: "4",
    title: "Mystic Peaks",
    description: "A small town is plagued by supernatural occurrences after a mysterious artifact is discovered. The source of the mystery is unveiled at the end of season 1.",
    coverImageUrl: "https://picsum.photos/seed/mystic/300/450",
    totalEpisodes: 8,
    watchedEpisodes: 3,
    status: "Dropped",
    genres: ["Supernatural", "Horror", "Mystery"],
    rating: 7.0,
    spoilersVisible: false,
    releaseYear: 2023,
  },
  {
    id: "5",
    title: "Galactic Guardians",
    description: "A team of unlikely heroes band together to protect the galaxy from an ancient evil. Features a surprise villain reveal.",
    coverImageUrl: "https://picsum.photos/seed/galactic/300/450",
    totalEpisodes: 24,
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Sci-Fi", "Action", "Comedy"],
    rating: 9.0,
    spoilersVisible: false,
    releaseYear: 2024,
  },
  {
    id: "6",
    title: "Chronicles of Eldoria",
    description: "A sprawling fantasy epic about a young sorceress destined to save her world from encroaching darkness. The prophecy is a key plot point.",
    coverImageUrl: "https://picsum.photos/seed/eldoria/300/450",
    totalEpisodes: 10,
    watchedEpisodes: 5,
    status: "Watching",
    genres: ["Fantasy", "Adventure"],
    rating: 8.9,
    spoilersVisible: false,
    userScore: 9,
    releaseYear: 2023,
  },
  {
    id: "7",
    title: "Attack on Titan",
    description: "Humanity fights for survival against giant man-eating humanoids. Many plot twists and character developments.",
    coverImageUrl: "https://picsum.photos/seed/aot/300/450",
    totalEpisodes: 87,
    watchedEpisodes: 87,
    status: "Completed",
    genres: ["Anime", "Action", "Dark Fantasy", "Post-apocalyptic"],
    rating: 9.0,
    spoilersVisible: true,
    userScore: 10,
    releaseYear: 2013,
  },
  {
    id: "8",
    title: "Jujutsu Kaisen",
    description: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    coverImageUrl: "https://picsum.photos/seed/jjk/300/450",
    totalEpisodes: 47, 
    watchedEpisodes: 24, 
    status: "Watching",
    genres: ["Anime", "Supernatural", "Action", "Dark Fantasy"],
    rating: 8.7,
    spoilersVisible: false,
    userScore: 9,
    releaseYear: 2020,
  },
  {
    id: "9",
    title: "Frieren: Beyond Journey's End",
    description: "After a ten-year quest, an elf mage and her companions defeat the Demon King. Now, Frieren must face the fleeting nature of time and the mortality of her friends.",
    coverImageUrl: "https://picsum.photos/seed/frieren/300/450",
    totalEpisodes: 28, 
    watchedEpisodes: 0, 
    status: "Plan to Watch",
    genres: ["Anime", "Fantasy", "Adventure", "Slice of Life"],
    rating: 9.4, 
    spoilersVisible: false,
    releaseYear: 2023, 
  },
  {
    id: "10",
    title: "Chainsaw Man",
    description: "Denji has a simple dream—to live a happy and peaceful life. This is a far cry from reality, as Denji is forced by the yakuza into killing devils to pay off his debts.",
    coverImageUrl: "https://picsum.photos/seed/csm/300/450",
    totalEpisodes: 12,
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Anime", "Action", "Dark Fantasy", "Supernatural"],
    rating: 8.9,
    spoilersVisible: false,
    releaseYear: 2022,
  },
  {
    id: "11",
    title: "Spy x Family",
    description: "A spy on an undercover mission gets married and adopts a child, not realizing his new wife is an assassin and his new daughter is a telepath.",
    coverImageUrl: "https://picsum.photos/seed/spyxfamily/300/450",
    totalEpisodes: 25, // Season 1 total, can be updated if more seasons are covered
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Anime", "Comedy", "Action", "Slice of Life"],
    rating: 8.6,
    spoilersVisible: false,
    releaseYear: 2022,
  },
  {
    id: "12",
    title: "Vinland Saga Season 2",
    description: "Thorfinn seeks a new purpose in life after the death of Askeladd, journeying to find Vinland, while new conflicts arise.",
    coverImageUrl: "https://picsum.photos/seed/vinland2/300/450",
    totalEpisodes: 24,
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Anime", "Action", "Adventure", "Drama", "Historical"],
    rating: 9.1,
    spoilersVisible: false,
    releaseYear: 2023,
  },
  {
    id: "13",
    title: "Solo Leveling",
    description: "In a world where hunters with magical abilities battle deadly monsters to protect humanity, a notoriously weak hunter gains extraordinary power.",
    coverImageUrl: "https://picsum.photos/seed/sololeveling/300/450",
    totalEpisodes: 12, // For Season 1
    watchedEpisodes: 0,
    status: "Plan to Watch",
    genres: ["Anime", "Action", "Fantasy", "Adventure"],
    rating: 8.5, // Hypothetical, as it's new
    spoilersVisible: false,
    releaseYear: 2024,
  }
];

export const mockClubs: Club[] = [
  {
    id: "c1",
    name: "Sci-Fi Mavericks",
    description: "A club for lovers of all things science fiction, from classic novels to modern blockbusters.",
    memberCount: 125,
    coverImageUrl: "https://picsum.photos/seed/scificlub/400/200",
    tags: ["Sci-Fi", "Movies", "TV Shows", "Books"],
  },
  {
    id: "c2",
    name: "Fantasy Fanatics",
    description: "Discuss your favorite fantasy series, theories, and upcoming adaptations.",
    memberCount: 210,
    coverImageUrl: "https://picsum.photos/seed/fantasyclub/400/200",
    tags: ["Fantasy", "Epic Fantasy", "Urban Fantasy"],
  },
  {
    id: "c3",
    name: "Anime Watchers Unite",
    description: "From Shonen to Shojo, seasonal anime discussions and recommendations.",
    memberCount: 350,
    coverImageUrl: "https://picsum.photos/seed/animeclub/400/200",
    tags: ["Anime", "Manga", "Seasonal"],
  },
   {
    id: "c4",
    name: "Thriller Thursday",
    description: "Dedicated to suspenseful thrillers and mind-bending mysteries.",
    memberCount: 88,
    coverImageUrl: "https://picsum.photos/seed/thrillerclub/400/200",
    tags: ["Thriller", "Mystery", "Suspense", "Crime"],
  },
];
